WIP unification of modal dialogs for errors and such
TASVideos/BizHawk pull request #2579
Opened 2021-01-18 04:57 UTC by YoshiRulz

2021-03-10 01:19 UTC, adelikat requested changes
Put that interface in BizHawk.Client.Common instead of Bizhawk.Common and I will approve.  But it is a client specific concern.  Common is reserved for completely agnostic code.

2021-03-10 01:24 UTC, YoshiRulz commented
I'm using it in `CoreComm`, in the `BizHawk.Emulation.Common` project. Shall I revert that, move the interface, and merge the rest?

2021-03-10 01:33 UTC, adelikat commented
Unfortunately, yeah.  At least for now.  It doesn't feel right in CoreComm either, it is such a client ui specific thing, I'd like to see it avoided in CoreComm as well, and keep it to generic callbacks

2021-03-24 00:08 UTC, adelikat approved these changes

2021-03-24 00:08 UTC, merged